[tool.poetry]
name = "dvc"
version = "0.1.0"
description = ""
authors = ["GTrunSec <gtrunsec@hardenedlinux.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
colorama = ">=0.3.9"
configobj = ">=5.0.6"
voluptuous = ">=0.11.7"
requests = ">=2.22.0"
grandalf = "0.6"
distro = ">=1.3.0"
appdirs = ">=1.4.3"
ruamel-yaml = ">=0.17.11"
tomlkit = ">=0.11.1"
funcy = ">=1.14"
pathspec = ">=0.9.0"
shortuuid = ">=0.5.0"
tqdm = ">=4.63.1,<5"
filelock = "==3.9.0"
packaging = ">=19.0"
zc-lockfile = ">=1.2.1"
flufl-lock = ">=5"
networkx = ">=2.5"
psutil = ">=5.8.0"
pydot = ">=1.2.4"
importlib-resources = ">=5.2.2"
flatten-dict = ">=0.4.1,<1"
tabulate = ">=0.8.7"
pygtrie = ">=2.3.2"
dpath = ">=2.0.2,<3"
shtab = ">=1.3.4,<2"
rich = ">=10.13.0"
pyparsing = ">=2.4.7"
typing-extensions = ">=3.7.4"
scmrepo = "0.1.5"
dvc-render = "0.0.17"
dvc-task = "0.1.9"
dvclive = ">=1.2.2"
dvc-data = "0.28.4"
dvc-http = "2.27.2"
hydra-core = ">=1.1.0"
iterative-telemetry = "0.0.6"
dvc-studio-client = ">=0.1.1"
hatchling = "<=1.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
