[tool.poetry]
name = "prefect-poetry"
version = "0.1.0"
description = ""
authors = ["GTrunSec <gtrunsec@hardenedlinux.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
aiosqlite = ">=0.17.0"
alembic = ">=1.7.5"
anyio = ">=3.4.0"
apprise = ">=1.1.0"
asgi-lifespan = ">=1.0"
asyncpg = ">=0.23"
click = ">=8.0,<8.2"
cloudpickle = ">=2.0"
coolname = ">=1.0.4"
croniter = ">=1.0.12"
cryptography = ">=36.0.1"
docker = ">=4.0"
fastapi = ">=0.70"
fsspec = ">=2022.5.0"
griffe = ">=0.20.0"
httpx = { version = ">=0.23", extras = ["http2"] }
importlib-metadata = { version = ">=4.4", markers = "python_version < \"3.10\"" }
jsonpatch = ">=1.32"
kubernetes = ">=24.2.0"
orjson = ">=3.7"
packaging = ">=21.3"
pathspec = ">=0.8.0"
pendulum = ">=2.1.2"
pydantic = ">=1.10.0"
python-slugify = ">=5.0"
pytz = ">=2021.1"
pyyaml = ">=5.4.1"
readchar = ">=4.0.0"
rich = ">=11.0"
sqlalchemy = { version = ">=1.4.20,<1.4.33 || >1.4.33", extras = ["asyncio"] }
toml = ">=0.10.0"
typer = ">=0.4.2"
typing-extensions = ">=4.1.0"
uvicorn = ">=0.14.0"

[tool.poetry.group.jupyter.dependencies]
ipykernel = "^6.19.2"
papermill = "^2.4.0"
nbconvert = "^7.2.6"

[tool.poetry.group.aws.dependencies]
botocore = "^1.29.27"
boto3 = "^1.26.27"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
