[prefect]
src.github_tag = "PrefectHQ/prefect"
fetch.github = "PrefectHQ/prefect"

[prefect-latest]
src.git = "https://github.com/PrefectHQ/prefect"
fetch.git = "https://github.com/PrefectHQ/prefect"
