[tool.poetry]
name = "kedro-poetry"
version = "0.1.0"
description = ""
authors = ["GTrunSec <gtrunsec@hardenedlinux.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
attrs = ">=21.3"
cachetools = ">=4.1,<5.0"
click = "<9.0"
cookiecutter = "^2.1.1"
dynaconf = "^3.1.11"
fsspec = "^2022.11.0"
gitpython = ">=3.0,<4.0"
importlib-metadata = "^5.2.0"
importlib-resources = ">=1.3"
jmespath = ">=0.9.5,<1.0"
omegaconf = ">=2.3,<3.0"
pluggy = ">=1.0.0,<1.1.0"
pyyaml = "^6.0"
rich = ">=12.0,<13.0"
rope = "~=1.5.1"
setuptools = ">=65.5.1"
toml = ">=0.10,<1.0"
toposort = ">=1.7,<2.0"
anyconfig = "~=0.10.0"
# extraPackage
pip-tools = "^6.12.1"

[tool.poetry.group.kedro-viz.dependencies]
fastapi = ">=0.73.0,<0.86.0"
pandas = "^1.5.2"
sqlalchemy = ">=1.4,<2.0"
ipython = ">=7.0.0,<9.0"
strawberry-graphql = ">=0.99.0,<1.0"
networkx = ">=1.0"
uvicorn = {version = ">=0.20.0,<0.21.0", extras = ["standard"]}
watchgod = ">=0.8.2,<0.9.0"
plotly = ">=4.0"
aiofiles = "22.1.0"
semver = ">=2.13,<3.0"
orjson = ">=3.8,<4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
