name: "CI"
on:
  pull_request:
  push:
  schedule:
    - cron: "0 0 * * SUN" # every sunday
jobs:
  nix-tests:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 0

    - uses: cachix/install-nix-action@v16
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.7.0pre20220127_558c4ee/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          system-features = nixos-test benchmark big-parallel kvm recursive-nix

    # CI workflows

    - name: Run Nix Flake Show
      run: nix flake show

    - name: Run Nvfetcher Updates
      run: |
        nix flake update
        nix -Lv develop github:hardenedlinux/nixpkgs-hardenedlinux -c update nvfetcher ./nix/sources.toml


    - name: Nix Build with airflow-frontend
      run: nix -Lv build ./#airflow-frontend

    - name: Nix Build with airflow Release
      run: nix -Lv build ./#airflow-release

    - name: Nix Build with airflow Latest
      continue-on-error: true
      run: nix -Lv build ./#airflow-latest

    - name: Check Airflow Exec
      run: nix -Lv develop -c airflow info

    # - name: Check Airflow Service
    #   run: nix build ./#airflow-vm-systemd --print-build-logs

    - name: Commit changes
      if: ${{ env.COMMIT_MSG != null }}
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ${{ env.COMMIT_MSG }}
